Repository antvis/AVA, pull requests merged in 2020-10, with the labels that each got.

#81 refactor: apply new pipeline to auto chart exclude config pannel
  demo/FindInsightTest/index.tsx
  demo/app.tsx
  packages/chart-advisor/__tests__/index.test.ts
  packages/chart-advisor/__tests__/unit/plots/column.test.ts
  packages/chart-advisor/src/adapt-render.ts
  packages/chart-advisor/src/advice-pipeline/g2-render.ts
  packages/chart-advisor/src/advice-pipeline/interface.ts
  packages/chart-advisor/src/advice-pipeline/spec-to-libconfig.ts
  packages/chart-advisor/src/advisor.ts
  packages/chart-advisor/src/auto-chart.ts
  packages/chart-advisor/src/auto-plot.ts
  packages/chart-advisor/src/chartLibMapping/G2.ts
  packages/chart-advisor/src/chartLibMapping/index.ts
  packages/chart-advisor/src/index.ts
  packages/chart-advisor/src/toolbar.ts
Labels: PR: reviewed-approved, refactor

#82 chore: declare untypes modules
  packages/chart-advisor/src/advice-pipeline/dataprops-to-specs.ts
  packages/chart-advisor/src/advice-pipeline/index.ts
  packages/chart-advisor/src/advice-pipeline/interface.ts
  packages/chart-advisor/src/advice-pipeline/spec-to-libconfig.ts
  packages/chart-advisor/src/types/index.d.ts
Labels: PR: reviewed-approved, chore

#83 style: solve api extractor warnings
  common/reviews/api/chart-advisor.api.md
  packages/chart-advisor/src/advice-pipeline/index.ts
  packages/chart-advisor/src/advice-pipeline/interface.ts
  packages/chart-advisor/src/advice-pipeline/vega-lite.ts
  packages/chart-advisor/src/chartLibMapping/index.ts
  packages/chart-advisor/src/index.ts
Labels: PR: reviewed-approved, style

#85 V1 refactor
  demo/PipelineTest.tsx
  demo/app.tsx
  demo/data-samples/interfaces.ts
  packages/chart-advisor/__tests__/unit/pipeline/data-to-dataprops.test.ts
  packages/chart-advisor/__tests__/unit/pipeline/data-to-specs.test.ts
  packages/chart-advisor/__tests__/unit/pipeline/dataprops-to-advices.test.ts
  packages/chart-advisor/__tests__/unit/pipeline/render.test.ts
  packages/chart-advisor/__tests__/unit/pipeline/spec-render.test.ts
  packages/chart-advisor/__tests__/unit/pipeline/spec-to-libconfig.test.ts
  packages/chart-advisor/__tests__/unit/plots/column.test.ts
  packages/chart-advisor/src/advice-pipeline/data-to-dataprops.ts
  packages/chart-advisor/src/advice-pipeline/dataprops-to-advices.ts
  packages/chart-advisor/src/advice-pipeline/g2-render.ts
  packages/chart-advisor/src/advice-pipeline/index.ts
  packages/chart-advisor/src/advice-pipeline/interface.ts
  packages/chart-advisor/src/advice-pipeline/spec-mapping.ts
  packages/datawizard/analyzer/__tests__/index.test.ts
  packages/datawizard/analyzer/src/index.ts
Labels: PR: reviewed-changes-requested
