Repository antvis/AVA, pull requests merged in 2020-02, with the labels that each got.

#11 docs: markdownlint
  .markdownlint.json
  README.md
  zh-CN/EXAMPLES.zh-CN.md
  zh-CN/README.zh-CN.md
Labels: documentation

#16 docs(datawizard): readme
  README.md
  packages/datawizard/README.md
  packages/datawizard/zh-CN/README.zh-CN.md
  packages/knowledge/README.md
  packages/knowledge/zh-CN/README.zh-CN.md
  zh-CN/README.zh-CN.md
Labels: documentation

#21 docs(readme): contribution
  README.md
  packages/knowledge/zh-CN/CONTRIBUTING.zh-CN.md
  zh-CN/CONTRIBUTING.zh-CN.md
  zh-CN/README.zh-CN.md
Labels: documentation

#19 fix: error when date is null for #18
  packages/datawizard/analyzer/__tests__/index.test.ts
  packages/datawizard/analyzer/src/utils.ts
Labels: bug

#23 perf: use the filtered well array to prorcess
  packages/datawizard/analyzer/src/index.ts
Labels: performance

#29 fix(ckb): fix chart dataPres bug
  packages/knowledge/src/base.ts
Labels: bug

#26 fix(datawizard): analyzer.analyzeDate must return original value of t…
  packages/datawizard/analyzer/__tests__/index.test.ts
  packages/datawizard/analyzer/src/index.ts
  packages/datawizard/analyzer/src/statistic.ts
Labels: bug
