Repository antvis/AVA, pull requests merged in 2020-11, with the labels that each got.

#87 feat: optimize demo ui
  .babelrc
  demo/PipelineTest.tsx
  demo/app.tsx
  demo/index.less
  demo/table.less
  package.json
  webpack.config.js
Labels: PR: reviewed-approved

#89 chore: improve site istart
  packages/ava-site/.eslintrc.js
  packages/ava-site/gatsby-browser.js
  packages/ava-site/package.json
Labels: PR: unreviewed

#93 Feature/add new chart desc
  packages/knowledge/src/base.ts
  packages/knowledge/src/i18n/zh-CN.ts
Labels: PR: reviewed-approved

#92 chore: init gh-pages site
  lerna.json
  package.json
  packages/ava-site/.eslintrc.js
  packages/ava-site/.gitignore
  packages/ava-site/LICENSE
  packages/ava-site/docs/api/auto-chart.en.md
  packages/ava-site/docs/api/auto-chart.zh.md
  packages/ava-site/docs/tutorial/getting-started.en.md
  packages/ava-site/docs/tutorial/getting-started.zh.md
  packages/ava-site/examples/basic/API.en.md
  packages/ava-site/examples/basic/API.zh.md
  packages/ava-site/examples/basic/demo/basic.js
  packages/ava-site/examples/basic/demo/meta.json
  packages/ava-site/examples/basic/index.en.md
  packages/ava-site/examples/basic/index.zh.md
  packages/ava-site/examples/gallery/index.en.md
  packages/ava-site/examples/gallery/index.zh.md
  packages/ava-site/externals.d.ts
  packages/ava-site/gatsby-browser.js
  packages/ava-site/gatsby-config.js
  packages/ava-site/gatsby-node.js
  packages/ava-site/package.json
  packages/ava-site/site/locale.json
  packages/ava-site/site/pages/index.en.tsx
  packages/ava-site/site/pages/index.zh.tsx
Labels: PR: reviewed-approved

#95 Mirror
  .github/workflows/mirror.yml
  packages/ava-site/package.json
  packages/knowledge/__tests__/pack.test.ts
  packages/knowledge/src/base.ts
  packages/knowledge/src/i18n/zh-CN.ts
  packages/knowledge/zh-CN/README.zh-CN.md
Labels: PR: unreviewed

#99 feat(site): new banner image
  packages/ava-site/site/pages/index.zh.tsx
Labels: PR: reviewed-approved

#98 feat(CKB): add radial bar chart spec
  packages/knowledge/__tests__/pack.test.ts
  packages/knowledge/src/base.ts
  packages/knowledge/src/i18n/zh-CN.ts
Labels: PR: reviewed-approved

#97 feat(CKB): add outlier to the purposes
  common/reviews/api/knowledge.api.md
  docs/api/knowledge.purpose_options.md
  packages/knowledge/__tests__/pack.test.ts
  packages/knowledge/src/base.ts
  packages/knowledge/src/chartID.ts
  packages/knowledge/src/i18n/zh-CN.ts
  packages/knowledge/src/interface.ts
Labels: PR: reviewed-approved

#101 feat(CKB): add ordinal in bar/column/pie charts
  packages/knowledge/src/base.ts
Labels: PR: reviewed-approved

#102 autochart ui & design rules
  demo/AutoChartTest.tsx
  demo/FindInsightTest/g2plot-config.ts
  demo/FindInsightTest/index.tsx
  demo/PipelineTest.tsx
  demo/app.tsx
  demo/auto-chart.tsx
  demo/index.less
  docs/api/chart-advisor.advisoroptions.chartRuleConfigs.md
  docs/api/chart-advisor.advisoroptions.refine.md
  docs/api/chart-advisor.autochartoptions.md
  package.json
  packages/chart-advisor/package.json
  packages/chart-advisor/src/advice-pipeline/dataprops-to-advices.ts
  packages/chart-advisor/src/advice-pipeline/index.ts
  packages/chart-advisor/src/advice-pipeline/interface.ts
  packages/chart-advisor/src/advice-pipeline/spec-mapping.ts
  packages/chart-advisor/src/advice-pipeline/spec-to-libconfig.ts
  packages/chart-advisor/src/auto-chart.ts
  packages/chart-advisor/src/auto-plot.ts
  packages/chart-advisor/src/chartLibMapping/index.ts
  packages/chart-advisor/src/config-panel.ts
  packages/chart-advisor/src/dev-panel.ts
  packages/chart-advisor/src/dummy-plot.ts
  packages/chart-advisor/src/index.ts
  packages/chart-advisor/src/mock-panel.ts
  packages/chart-advisor/src/rules/concepts/designRule.ts
  packages/chart-advisor/src/rules/concepts/rule.ts
  packages/chart-advisor/src/rules/designRules.ts
  packages/chart-advisor/src/rules/index.ts
  packages/chart-advisor/src/rules/rules.ts
  packages/chart-advisor/src/style.ts
  packages/chart-advisor/src/toolbar.ts
  packages/chart-advisor/src/util.ts
Labels: PR: reviewed-changes-requested

#108 chore(site): add notifications in home page
  packages/ava-site/site/locale.json
  packages/ava-site/site/pages/index.zh.tsx
Labels: PR: unreviewed
