Repository antvis/AVA, pull requests merged in 2020-03, with the labels that each got.

#30 feat: knowledge about graph and map in CKB
  packages/knowledge/src/base.ts
  packages/knowledge/src/interface.ts
Labels: enhancement

#31 feat(ckb): add chart types and props
  packages/knowledge/__tests__/options.test.ts
  packages/knowledge/__tests__/pack.test.ts
  packages/knowledge/src/base.ts
  packages/knowledge/src/chartID.ts
  packages/knowledge/src/i18n/interface.ts
  packages/knowledge/src/i18n/zh-CN.ts
  packages/knowledge/src/interface.ts
  packages/knowledge/src/options.ts
Labels: enhancement

#32 fix: heatmap purpose to distribution
  packages/knowledge/src/base.ts
  packages/knowledge/src/interface.ts
Labels: bug

#34 fix(ckb): merge single-multi and basic-multi charts into one
  packages/knowledge/__tests__/pack.test.ts
  packages/knowledge/src/base.ts
  packages/knowledge/src/chartID.ts
  packages/knowledge/src/i18n/zh-CN.ts
  packages/knowledge/src/pack.ts
Labels: bug

#37 Advisor doc
  CONTRIBUTING.md
  EXAMPLES.md
  README.md
  packages/chart-advisor/API.md
  packages/chart-advisor/README.md
  packages/chart-advisor/zh-CN/API.zh-CN.md
  packages/chart-advisor/zh-CN/README.zh-CN.md
  packages/knowledge/CONTRIBUTING.md
  packages/knowledge/README.md
  zh-CN/CONTRIBUTING.zh-CN.md
  zh-CN/EXAMPLES.zh-CN.md
  zh-CN/README.zh-CN.md
Labels: PR: reviewed-changes-requested
