Repository antvis/AVA, pull requests merged in 2020-05, with the labels that each got.

#58 dw-transform pack
  lerna.json
  packages/chart-advisor/package.json
  packages/datawizard/analyzer/package.json
  packages/datawizard/transform/.npmignore
  packages/datawizard/transform/package.json
  packages/datawizard/transform/webpack.config.js
Labels: PR: reviewed-changes-requested

#67 Transform doc
  common/reviews/api/dw-transform.api.md
  lerna.json
  packages/chart-advisor/package.json
  packages/datawizard/analyzer/package.json
  packages/datawizard/transform/LICENSE
  packages/datawizard/transform/README.md
  packages/datawizard/transform/__tests__/autoTransform.test.ts
  packages/datawizard/transform/package.json
  packages/datawizard/transform/src/autoTransform.ts
  packages/datawizard/transform/src/index.ts
Labels: PR: reviewed-changes-requested

#68 Fix transform typo
  docs/api/dw-transform.autoschema.md
  docs/api/dw-transform.autotransform.md
  docs/api/dw-transform.autotransformresult.md
  docs/api/dw-transform.autotransformresult.result.md
  docs/api/dw-transform.autotransformresult.schemas.md
  docs/api/dw-transform.md
  docs/api/dw-transform.renameoption.md
  docs/api/dw-transforms.aggregate.md
  docs/api/dw-transforms.aggregateparams.as.md
  docs/api/dw-transforms.aggregateparams.fields.md
  docs/api/dw-transforms.aggregateparams.groupby.md
  docs/api/dw-transforms.aggregateparams.md
  docs/api/dw-transforms.aggregateparams.op.md
  docs/api/dw-transforms.md
  docs/api/index.md
  lerna.json
  packages/datawizard/transform/package.json
  packages/datawizard/transform/src/index.ts
Labels: PR: unreviewed

#62 feat: test insights with visual-insights' default workers
  demo/FindInsightTest.tsx
  demo/FindInsightTest/Charts.tsx
  demo/FindInsightTest/index.tsx
  demo/app.tsx
  demo/utils.tsx
  package.json
  packages/chart-advisor/__tests__/insight.test.ts
  packages/chart-advisor/package.json
  packages/chart-advisor/src/insight/index.ts
Labels: PR: unreviewed, enhancement
