Repository antvis/AVA, pull requests merged in 2021-09, with the labels that each got.

#237 chore: fix @babel/runtime module find error
  demo/package.json
  demo/webpack.config.js
Labels: PR: unreviewed

#238 feat(DW): allow slice during constructing
  packages/data-wizard/__tests__/dataset/data-frame.test.ts
  packages/data-wizard/src/dataset/data-frame.ts
Labels: PR: unreviewed

#236 feat(SmartBoard): add smartboard demo
  demo/src/demos/SmartBoard/ChartSamples/chartSample1.ts
  demo/src/demos/SmartBoard/ChartSamples/chartSample2.ts
  demo/src/demos/SmartBoard/ChartSamples/index.ts
  demo/src/demos/SmartBoard/Page/ChartView.tsx
  demo/src/demos/SmartBoard/Page/Dashboard.tsx
  demo/src/demos/SmartBoard/Page/Toolbar.tsx
  demo/src/demos/SmartBoard/Page/index.less
  demo/src/demos/SmartBoard/Page/index.tsx
  demo/src/demos/SmartBoard/index.tsx
  demo/src/demos/SmartBoard/utils/aggregate.ts
  demo/src/demos/SmartBoard/utils/chartInfo2Config.ts
  demo/src/demos/SmartBoard/utils/g2plotRender.ts
  demo/src/demos/SmartBoard/utils/index.ts
  demo/src/manifest.tsx
Labels: PR: reviewed-changes-requested

#243 feat(CA): simple demo of CA
  demo/package.json
  demo/src/demos/ChartAdvisor/Advisor/AdviceCard.tsx
  demo/src/demos/ChartAdvisor/Advisor/AdvisorPanel.tsx
  demo/src/demos/ChartAdvisor/CA/CACard.tsx
  demo/src/demos/ChartAdvisor/CA/CAPanel.tsx
  demo/src/demos/ChartAdvisor/Chart.tsx
  demo/src/demos/ChartAdvisor/ChartAdvisor.tsx
  demo/src/demos/ChartAdvisor/Linter/LintCard.tsx
  demo/src/demos/ChartAdvisor/Linter/LinterPanel.tsx
  demo/src/demos/ChartAdvisor/data.json
  demo/src/demos/ChartAdvisor/index.tsx
  demo/src/manifest.tsx
Labels: PR: reviewed-approved

#245 feat(advisor): add rule trigger
  packages/chart-advisor/src/advisor/advice-pipeline/data-to-advices.ts
  packages/chart-advisor/src/linter/index.ts
  packages/chart-advisor/src/ruler/concepts/rule.ts
  packages/chart-advisor/src/ruler/rules/aggregation-single-row.ts
  packages/chart-advisor/src/ruler/rules/all-can-be-table.ts
  packages/chart-advisor/src/ruler/rules/bar-series-qty.ts
  packages/chart-advisor/src/ruler/rules/data-check.ts
  packages/chart-advisor/src/ruler/rules/data-field-qty.ts
  packages/chart-advisor/src/ruler/rules/diff-pie-sector.ts
  packages/chart-advisor/src/ruler/rules/landscape-or-portrait.ts
  packages/chart-advisor/src/ruler/rules/limit-series.ts
  packages/chart-advisor/src/ruler/rules/line-field-time-ordinal.ts
  packages/chart-advisor/src/ruler/rules/no-redundant-field.ts
  packages/chart-advisor/src/ruler/rules/nominal-enum-combinatorial.ts
  packages/chart-advisor/src/ruler/rules/purpose-check.ts
  packages/chart-advisor/src/ruler/rules/series-qty-limit.ts
  packages/chart-advisor/src/ruler/rules/x-axis-line-fading.ts
Labels: PR: partially-approved

#244 feat(lite-insight): update annotation
  packages/lite-insight/src/visualization/annotation.ts
  packages/lite-insight/src/visualization/util.ts
Labels: PR: unreviewed

#253 refactor(DW): change DW abbr to complete spelling
  packages/chart-advisor/src/advisor/advice-pipeline/spec-mapping.ts
  packages/data-wizard/__tests__/dataset/data-frame.test.ts
  packages/data-wizard/__tests__/dataset/series.test.ts
  packages/data-wizard/src/analyzer/index.ts
  packages/data-wizard/src/dataset/base-frame.ts
  packages/data-wizard/src/dataset/data-frame.ts
  packages/data-wizard/src/dataset/series.ts
  packages/data-wizard/src/dataset/utils.ts
  packages/data-wizard/src/index.ts
  packages/data-wizard/src/statistics/index.ts
  packages/data-wizard/src/utils/index.ts
Labels: PR: partially-approved

#250 feat(lite-insight): homogeneous pattern
  demo/src/demos/LiteInsight/AutoInsight.tsx
  packages/lite-insight/src/algorithms/pettitt-test.ts
  packages/lite-insight/src/constant.ts
  packages/lite-insight/src/insights/checkers.ts
  packages/lite-insight/src/insights/extractors/categoryOutlier.ts
  packages/lite-insight/src/insights/extractors/changePoint.ts
  packages/lite-insight/src/insights/extractors/timeSeriesOutlier.ts
  packages/lite-insight/src/insights/extractors/trend.ts
  packages/lite-insight/src/insights/index.ts
  packages/lite-insight/src/interface.ts
  packages/lite-insight/src/pipeline/homogeneous.ts
  packages/lite-insight/src/pipeline/index.ts
  packages/lite-insight/src/pipeline/insight.ts
  packages/lite-insight/src/pipeline/preprocess.ts
  packages/lite-insight/src/pipeline/util.ts
  packages/lite-insight/src/utils/aggregate.ts
  packages/lite-insight/src/visualization/annotation.ts
  packages/lite-insight/src/visualization/description.ts
  packages/lite-insight/src/visualization/index.ts
  packages/lite-insight/src/visualization/util.ts
Labels: PR: unreviewed

#258 fix(CA): fix bug in test
  packages/chart-advisor/__tests__/rule.test.ts
Labels: PR: reviewed-approved

#254 fix(style): fix the UI of title view
  demo/src/demos/SmartBoard/ChartSamples/chartSample1.ts
  demo/src/demos/SmartBoard/ChartSamples/chartSample2.ts
  demo/src/demos/SmartBoard/ChartSamples/index.ts
  demo/src/demos/SmartBoard/Page/ChartView.tsx
  demo/src/demos/SmartBoard/Page/Dashboard.tsx
  demo/src/demos/SmartBoard/Page/Toolbar.tsx
  demo/src/demos/SmartBoard/Page/index.less
  demo/src/demos/SmartBoard/Page/index.tsx
  packages/smart-board/package.json
  packages/smart-board/src/interfaces.ts
Labels: PR: reviewed-approved

#259 feat(CA): config primary color
  demo/src/demos/ChartAdvisor/Advisor/AdvisorPanel.tsx
  packages/chart-advisor/package.json
  packages/chart-advisor/src/advisor/advice-pipeline/data-to-advices.ts
  packages/chart-advisor/src/advisor/advice-pipeline/interface.ts
Labels: PR: partially-approved

#263 feat: homogeneous insight annotation
  packages/lite-insight/src/visualization/annotation.ts
  packages/lite-insight/src/visualization/index.ts
Labels: PR: partially-approved

#264 chore(CA): limit-size
  packages/chart-advisor/package.json
Labels: PR: reviewed-approved

#266 fix(SmartBoard): modify the style of title info
  demo/src/demos/SmartBoard/ChartSamples/chartSample2.ts
  demo/src/demos/SmartBoard/Page/ChartView.tsx
  demo/src/demos/SmartBoard/Page/index.less
Labels: PR: reviewed-approved

#265 Enlarge li size
  packages/lite-insight/package.json
Labels: PR: reviewed-approved

#270 fix(CA): bugs when no input fields
  packages/chart-advisor/__tests__/index.test.ts
  packages/chart-advisor/src/advisor/index.ts
Labels: PR: partially-approved

#272 chore(site): revive ava site
  sites/ava-site/.eslintrc.js
  sites/ava-site/gatsby-browser.js
  sites/ava-site/gatsby-config.js
  sites/ava-site/jest.config.js
  sites/ava-site/package.json
Labels: PR: reviewed-approved

#275 fix(auto-chart): add auto-chart build set
  packages/auto-chart/package.json
  packages/auto-chart/rollup.config.js
Labels: PR: reviewed-approved

#276 docs(CA): readme and api
  packages/chart-advisor/API.md
  packages/chart-advisor/README.md
Labels: PR: partially-approved

#274 feat(insight): add change-point detection methods
  demo/src/demos/LiteInsight/AutoInsight.tsx
  packages/lite-insight/package.json
  packages/lite-insight/src/algorithms/BayesianChangePoint/BayesianChangePoint.ts
  packages/lite-insight/src/algorithms/BayesianChangePoint/Gamma.ts
  packages/lite-insight/src/algorithms/BayesianChangePoint/PDF.ts
  packages/lite-insight/src/algorithms/buishand-u.ts
  packages/lite-insight/src/algorithms/index.ts
  packages/lite-insight/src/algorithms/pettitt-test.ts
  packages/lite-insight/src/insights/extractors/changePoint.ts
Labels: PR: reviewed-approved
