Repository antvis/AVA, pull requests merged in 2021-05, with the labels that each got.

#159 fix(DW): date validator more strict
  lerna.json
  packages/ava-site/package.json
  packages/chart-advisor/package.json
  packages/datawizard/analyzer/__tests__/index.test.ts
  packages/datawizard/analyzer/__tests__/is-date.test.ts
  packages/datawizard/analyzer/package.json
  packages/datawizard/analyzer/src/index.ts
  packages/datawizard/analyzer/src/is-date.ts
  packages/datawizard/analyzer/src/utils.ts
  packages/datawizard/random/package.json
  packages/datawizard/transform/package.json
  packages/datawizard/utils/package.json
  packages/knowledge/package.json
Labels: PR: reviewed-approved

#163 chore: fix lint and bootstrap when pre commit
  package.json
Labels: PR: reviewed-approved

#166 fix(chart-advisor): add some i18n words
  packages/chart-advisor/src/i18n/locales/zh_CN.ts
Labels: PR: unreviewed

#162 feat(chart-advisor): support custom chart knowledge
  packages/chart-advisor/__tests__/unit/pipeline/dataprops-to-advices.test.ts
  packages/chart-advisor/src/advice-pipeline/dataprops-to-advices.ts
  packages/chart-advisor/src/advice-pipeline/index.ts
  packages/chart-advisor/src/advice-pipeline/interface.ts
  packages/chart-advisor/src/index.ts
  packages/chart-advisor/src/rules/rules.ts
Labels: PR: reviewed-approved

#167 fix(chart-advisor): adjust i18n locales
  packages/chart-advisor/src/i18n/locales/en_US.ts
  packages/chart-advisor/src/i18n/locales/zh_CN.ts
  packages/chart-advisor/src/mock-panel.ts
Labels: PR: reviewed-approved

#172 fix: readme not readable
  common/img/logo.svg
  common/img/vectorA.svg
  common/img/vectorASymbol.svg
Labels: PR: reviewed-approved

#177 chore: longer test timeout
  jest.config.js
Labels: PR: reviewed-approved

#179 fix(auto-chart): add pie statistic i18n patch
  packages/chart-advisor/src/auto-chart/auto-chart.ts
  packages/chart-advisor/src/auto-chart/auto-plot.ts
  packages/chart-advisor/src/i18n/locales/en_US.ts
  packages/chart-advisor/src/i18n/locales/zh_CN.ts
  packages/chart-linter/.gitignore
  packages/chart-linter/package.json
Labels: PR: reviewed-approved

#180 fix: generated phone numbers should not be real
  packages/datawizard/random/__tests__/text-random.test.ts
  packages/datawizard/random/src/text-random.ts
Labels: PR: reviewed-approved

#182 chore(chart-linter): update package.json
  packages/chart-linter/package.json
Labels: PR: partially-approved

#183 docs(chart-linter): update README
  README.md
  packages/chart-linter/README.md
  packages/chart-linter/zh-CN/README.zh-CN.md
Labels: PR: unreviewed
